- name: loops
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: install or uninstall packages
      ansible.builtin.package:
        name: "{{item.name}}"
        state: "{{item.state}}"
      loop:
        - {name: 'git', state: 'absent'}
        - {name: 'mysql', state: 'present'}
        - {name: 'java', state: 'present'}
