---
- hosts: all
  tasks:
    - name: update the system
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: upgrade the system packages
      apt: state=latest force_apt_get=yes
 
    - name: Install nessesary package
      apt:
        name: apt-transport-https
        state: present
        update_cache: yes

    - name: add grafana gpg key
      shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

    - name: add grafana repo
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana

    - name: Install grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Enable and start grafana service
      service:
        name: grafana-server
        enabled: yes
        state: started
