---
- hosts: all
  tasks:
    - name: update the system
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: upgrade the system packages
      apt: state=latest force_apt_get=yes

    - name: create prometheus system group
      group:
        name: prometheus
        system: true
        state: present

    - name: create prometheus system user
      user:
        name: prometheus
        system: true
        shell: "/usr/sbin/nologin"
        group: prometheus
        createhome: false
        home: "/var/lib/prometheus"

    - name: create prometheus data directory
      file:
        path: "/var/lib/prometheus"
        state: directory
        owner: prometheus
        group: prometheus
        mode: 0775

    - name: create prometheus configuration directories
      file:
        path: "/etc/prometheus"
        state: directory
        owner: prometheus
        group: prometheus
        mode: 0775

    - name: Download prometheus binary from official repo
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.43.0/prometheus-2.43.0.linux-amd64.tar.gz
        dest: /root
        mode: '0755'

    - name: Extract the prometheus binary
      unarchive:
        src: /root/prometheus-2.43.0.linux-amd64.tar.gz
        dest: /root
        remote_src: yes

    - name: move the prometheus and promtool binaries to bin folder
      command: mv /root/prometheus-2.43.0.linux-amd64/prometheus /usr/local/bin
      
    - name: move the prometheus and promtool binaries to bin folder
      command: mv /root/prometheus-2.43.0.linux-amd64/promtool /usr/local/bin

    - name: move console files to config directory
      command: mv /root/prometheus-2.43.0.linux-amd64/consoles/ /etc/prometheus
      ignore_errors: yes

    - name: move console files to config directory
      command: mv /root/prometheus-2.43.0.linux-amd64/console_libraries/ /etc/prometheus
      ignore_errors: yes

    - name: move prometheus.yml to config directory
      command: mv /root/prometheus-2.43.0.linux-amd64/prometheus.yml /etc/prometheus/prometheus.yml

    - name: create prometheus service file
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]  
          User=prometheus
          Group=prometheus
          Restart=always
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
              --config.file=/etc/prometheus/prometheus.yml \
              --storage.tsdb.path=/var/lib/prometheus/ \
              --web.console.templates=/etc/prometheus/consoles \
              --web.console.libraries=/etc/prometheus/console_libraries \
              --web.listen-address=0.0.0.0:9090

          [Install]
          WantedBy=multi-user.target

    - name: start and enable prometheus
      systemd:
        name: prometheus
        state: started
        daemon_reload: yes 
        enabled: yes
